import type { SampleItem } from "@/types/sample";

export const SAMPLE_DATA: SampleItem[] = [
  {
    id: "wood-coating-video",
    title: "木地板涂层产品15秒AI营销视频",
    category: "AI营销增长样品",
    clientType: "制造工厂、材料品牌、经销商",
    originalProblem: "产品技术优势难以在短时间内讲清，销售缺少可投放的视频素材。",
    diagnosisJudgment: "不应先铺大量内容，应先验证一个核心卖点能否在15秒内被目标客户理解。",
    productionLine: "AI营销增长生产线",
    deliverables: ["15秒成片", "产品卖点脚本", "分镜表", "多平台封面"],
    businessValue: "把技术参数转化为客户能理解的视觉卖点，用于销售演示和短视频获客。",
    extendableServices: ["系列产品视频", "详情页视觉", "渠道内容矩阵"],
    status: "已完成样品",
    assetStatus: "needs-replacement",
    mediaType: "video",
    mediaPlaceholder: "15秒产品营销视频演示位",
    realAssetNote: "后续替换真实成片、封面与分镜截图。"
  },
  {
    id: "product-visual",
    title: "企业产品图 / 详情页视觉升级样品",
    category: "AI营销增长样品",
    clientType: "品牌商、电商企业、传统制造企业",
    originalProblem: "现有产品图风格不统一，无法支撑官网、招商和电商渠道。",
    diagnosisJudgment: "先建立一套可复用的核心产品视觉模板，再扩展全产品线。",
    productionLine: "AI营销增长生产线",
    deliverables: ["产品主视觉", "场景图", "卖点信息图", "详情页模块"],
    businessValue: "低成本建立统一产品视觉系统，提高销售材料的专业度和复用率。",
    extendableServices: ["产品视频", "招商手册", "品牌内容规范"],
    status: "可定制",
    assetStatus: "mock",
    mediaType: "image",
    mediaPlaceholder: "产品主视觉与详情页演示位",
    realAssetNote: "后续替换真实产品图、场景图和详情页对比。"
  },
  {
    id: "founder-codex",
    title: "企业创始人Codex实战陪跑案例",
    category: "企业AI陪跑样品",
    clientType: "创始人、企业主、数字化负责人",
    originalProblem: "知道AI能开发产品，但不会把业务需求拆成可执行任务。",
    diagnosisJudgment: "问题不在工具，而在需求拆解与验收标准，适合真实项目陪跑。",
    productionLine: "企业AI陪跑生产线",
    deliverables: ["业务拆解", "Codex实操", "MVP共创", "复盘清单"],
    businessValue: "让企业负责人掌握从需求到可演示产品的完整方法，而不是只听概念。",
    extendableServices: ["团队训练营", "内部AI教练", "项目长期陪跑"],
    status: "已完成样品",
    assetStatus: "needs-replacement",
    mediaType: "document",
    mediaPlaceholder: "Codex陪跑过程与成果演示位",
    realAssetNote: "后续替换脱敏课程记录、任务拆解和MVP截图。"
  },
  {
    id: "ai-video-training",
    title: "企业AI视频制作训练案例",
    category: "企业AI陪跑样品",
    clientType: "市场团队、运营团队、销售团队",
    originalProblem: "团队缺少稳定的视频脚本、画面生成和剪辑工作流。",
    diagnosisJudgment: "需要训练一条标准生产流程，而不是继续零散学习更多工具。",
    productionLine: "企业AI陪跑生产线",
    deliverables: ["脚本模板", "画面提示词", "剪辑流程", "团队实战成片"],
    businessValue: "把零散工具变成团队可以重复执行的内容生产流程。",
    extendableServices: ["月度内容陪跑", "品牌素材库", "短视频矩阵"],
    status: "可定制",
    assetStatus: "mock",
    mediaType: "video",
    mediaPlaceholder: "AI视频训练成果演示位",
    realAssetNote: "后续替换团队实战成片和标准工作流截图。"
  },
  {
    id: "quote-project-mvp",
    title: "企业报价与项目管理系统MVP",
    category: "业务系统MVP样品",
    clientType: "项目制服务企业、工程公司、定制制造企业",
    originalProblem: "报价、合同、项目进度和回款信息分散在多个表格。",
    diagnosisJudgment: "先验证报价到项目交付的核心链路，不应直接建设复杂ERP。",
    productionLine: "业务系统MVP生产线",
    deliverables: ["报价工作台", "项目看板", "客户档案", "经营概览"],
    businessValue: "先用可演示MVP统一关键流程，再决定完整系统建设范围。",
    extendableServices: ["CRM集成", "审批流程", "财务接口"],
    status: "可演示MVP",
    assetStatus: "needs-replacement",
    mediaType: "system",
    mediaPlaceholder: "报价与项目管理系统演示位",
    realAssetNote: "后续替换脱敏后台截图或可访问Demo。"
  },
  {
    id: "sports-mini-program",
    title: "体育培训小程序管理后台MVP",
    category: "业务系统MVP样品",
    clientType: "培训机构、连锁门店、教练团队",
    originalProblem: "排课、学员、教练和消课记录依赖群聊与表格。",
    diagnosisJudgment: "先跑通管理后台核心流程，再评估家长端、支付和多门店能力。",
    productionLine: "业务系统MVP生产线",
    deliverables: ["学员管理", "课程排期", "消课记录", "运营数据"],
    businessValue: "验证机构核心管理流程，为小程序和多门店系统建设提供依据。",
    extendableServices: ["微信小程序", "支付接入", "家长端"],
    status: "可演示MVP",
    assetStatus: "needs-replacement",
    mediaType: "system",
    mediaPlaceholder: "体育培训管理后台演示位",
    realAssetNote: "后续替换学员、课程和消课管理真实界面。"
  },
  {
    id: "knowledge-demo",
    title: "企业知识库问答Demo",
    category: "企业知识库 / 客服Agent样品",
    clientType: "产品资料多、客服与销售问答重复的企业",
    originalProblem: "产品手册、案例和制度分散，员工无法快速找到可信答案。",
    diagnosisJudgment: "先用高频资料验证回答准确率，再决定是否接入全量知识和客服渠道。",
    productionLine: "效率自动化生产线",
    deliverables: ["资料清洗", "FAQ结构", "问答Demo", "引用来源"],
    businessValue: "缩短资料查找与新人培训时间，并降低错误回答风险。",
    extendableServices: ["客服Agent", "销售助手", "权限知识库"],
    status: "可演示MVP",
    assetStatus: "mock",
    mediaType: "system",
    mediaPlaceholder: "企业知识库问答演示位",
    realAssetNote: "后续替换脱敏问答记录、引用来源和命中率数据。"
  },
  {
    id: "excel-automation",
    title: "Excel / 报表自动整理流程Demo",
    category: "AI效率自动化样品",
    clientType: "财务、运营、供应链和项目管理团队",
    originalProblem: "多个Excel重复复制、核对、合并，月底报表耗时且容易出错。",
    diagnosisJudgment: "流程重复且规则明确，是最适合直接测量工时节省的自动化场景。",
    productionLine: "效率自动化生产线",
    deliverables: ["数据清洗", "表格合并", "异常校验", "自动报表"],
    businessValue: "直接减少重复工时，让高频报表流程可追踪、可复用。",
    extendableServices: ["定时任务", "飞书多维表格", "经营驾驶舱"],
    status: "已完成样品",
    assetStatus: "needs-replacement",
    mediaType: "document",
    mediaPlaceholder: "Excel与报表自动化演示位",
    realAssetNote: "后续替换输入表、处理规则和输出报表对比。"
  }
];
